# fly.toml file generated for notion-blog on 2022-10-12T16:02:48+05:30

app = "notion-blog"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  REACT_APP_BACKEND_URI="https://notion-blog.fly.dev"
  DJANGO_KEY="hg0$b@rixdadqlv^&tbkxqoh4dj+ky_tq2zx_8^vbyduzn(f$8ad9f2q3*(YUY97y98Y01IE20937GP08yf89h490FHJ8HF98HFP09SYS8(Y98Y*DD9yf9834hr93f#$(*"
  NOTION_TOKEN="secret_zYUFAxASmO0srxa1yzOEYcGsU6Ub0vRNXaRE6RXHur0"
  NOTION_DATABASE_ID="045eeab65ac04ca88c8b450a5deffcb2"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
